#!/bin/bash

while :; do
  if [[ -S "$HOME/.ssh/sock_kath.io_22_root" ]]; then
    ssh -Ct -S "$HOME/.ssh/sock_%h_%p_%r" root@kath.io 'screen -dr || screen'
  fi
  (( $? == 0 )) && exit 0
  sleep 1
done
