#!/bin/bash

while :; do
  if [[ -S "$HOME/.ssh/sock_root_kath.io_22" ]]; then
    ssh -Ct -S "$HOME/.ssh/sock_%r_%h_%p" root@kath.io 'screen -dr || screen'
  fi
  (( $? == 0 )) && exit 0
  sleep 1
done
