#!/bin/bash

while :; do
  ssh -CMN -c blowfish -D localhost:1080 -S "$HOME/.ssh/sock_%r_%h_%p"         \
    -o LocalCommand='echo Connected to %r@%h:%p >&2' -o PermitLocalCommand=yes \
    -o ServerAliveInterval=3 -o ServerAliveCountMax=1 -o TCPKeepAlive=no       \
    root@kath.io
  sleep 1
done
