#!/bin/bash

readonly user='kat'
readonly host='kath.io'
readonly port='22'
readonly socks_port='1080'

title() {
    echo -en "\033]2;${user}@${host}: $1\a"
}

opts=(
    -o Compression=yes
    -o DynamicForward="localhost:${socks_port}"
    -o EscapeChar=none
    -o LocalCommand="echo -en '$(title 'Connected 😃')'"
    -o PermitLocalCommand=yes
    -o Port="${port}"
    -o RequestTTY=force
    -o ServerAliveCountMax=1
    -o ServerAliveInterval=3
    -o TCPKeepAlive=no
    "${user}@${host}"
    'tmux attach || tmux'
)

title 'Making initial connection… 😐'
ssh "${opts[@]}"

while :; do
    title 'Reconnecting… 😣'
    ssh "${opts[@]}"
    sleep 1
done
